language: node_js

os:
  - osx

node_js:
  - node

install:
  - npm install

cache:
  directories:
    - "node_modules"

notifications:
  email:
    recipients:
      - bruno@logerfo.com.br
    on_success: never # default: change
    on_failure: always
